# Generated by Django 4.1.6 on 2023-04-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBA', '0004_profilecomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='player',
        ),
        migrations.AddField(
            model_name='band',
            name='members',
            field=models.ManyToManyField(related_name='bands', to='TBA.player'),
        ),
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.FloatField(),
        ),
    ]
