# Generated by Django 4.1.6 on 2023-04-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBA', '0005_remove_band_player_band_members_alter_review_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='guitar_player',
        ),
        migrations.AddField(
            model_name='album',
            name='cover_art',
            field=models.ImageField(blank=True, null=True, upload_to='TBA/static/album_covers/'),
        ),
        migrations.AddField(
            model_name='album',
            name='guitar_players',
            field=models.ManyToManyField(related_name='albums', to='TBA.player'),
        ),
        migrations.AddField(
            model_name='band',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='TBA/static/band_pics/'),
        ),
        migrations.AddField(
            model_name='player',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='TBA/static/player_pics/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.FloatField(choices=[(0, '0'), (0.5, '0.5'), (1, '1'), (1.5, '1.5'), (2, '2'), (2.5, '2.5'), (3, '3'), (3.5, '3.5'), (4, '4'), (4.5, '4.5'), (5, '5')]),
        ),
    ]
