# Generated by Django 4.1.6 on 2023-04-08 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TBA', '0007_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='TBA.player'),
        ),
    ]
