# Generated by Django 4.1.6 on 2023-04-09 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TBA', '0009_profilecomment_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilecomment',
            name='profile_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='profile_comments_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profilecomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_comments_posted', to=settings.AUTH_USER_MODEL),
        ),
    ]
