# Generated by Django 4.1.7 on 2023-04-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBA', '0012_band_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='player',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
