# Generated by Django 4.1.6 on 2023-04-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBA', '0014_gear_tonehunt_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='gear',
            field=models.ManyToManyField(related_name='gear_used', to='TBA.gear'),
        ),
    ]
