# Generated by Django 4.1.6 on 2023-05-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBA', '0018_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
