# Generated by Django 4.1.6 on 2023-05-14 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TBA', '0019_review_is_edited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='gear',
        ),
        migrations.AddField(
            model_name='comment',
            name='band',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='TBA.band'),
        ),
    ]
