# Generated by Django 4.1.6 on 2023-05-14 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TBA', '0020_remove_comment_gear_comment_band'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_comments_posted', to=settings.AUTH_USER_MODEL),
        ),
    ]
