# Generated by Django 4.1.6 on 2023-05-14 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TBA', '0021_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='gear',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='TBA.gear'),
        ),
    ]
