# Generated by Django 4.1.7 on 2023-05-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBA', '0026_alter_wishlist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='unknown.png', null=True, upload_to='TBA/static/profile_pics'),
        ),
    ]
