# Generated by Django 4.1.7 on 2023-05-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBA', '0027_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='TBA/static/profile_pics'),
        ),
    ]
